config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :home
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "perezalfredo14@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.valid?
      @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = "Cannot send message"
      render :index
    end
    render :index
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_contact.html.erb
<!-- Contact -->
<div id="contact" class="content-section-a">
  <div class="container">
    <div class="row">

      <div class="col-md-6 col-md-offset-3 text-center wrap_title">
        <h2>Contact Me</h2>
        <!-- <p class="lead" style="margin-top:0">A special thanks to Death.</p> -->
      </div>

      <%= render 'form' %>

      <hr class="featurette-divider hidden-lg">
      <div class="col-md-5 col-md-push-1 address">
        <address>
          <h3>Location</h3>
          <p class="lead"><a href="https://www.google.com/maps/place/505+NW+177th+St,+Miami+Gardens,+FL+33169/@25.9349753,-80.2096788,15.39z/data=!4m5!3m4!1s0x88d9ae67639dfe5d:0x9b6a60e92ab579d7!8m2!3d25.9371018!4d-80.2095625">Office<br>
            505 NW 177TH ST</a><br>
            Phone: 305-746-8004<br>
            Email: perezalfredo14@gmail.com</p>
          </address>

          <h3>Social</h3>
          <li class="social">
            <a href="https://www.flickr.com/gp/144774081@N07/3J4772"><i class="fa fa-flickr fa-size"> </i> </a>
          </li>
        </div>
      </div>
    </div>
  </div>

app/views/home/_education.html.erb
<!-- education -->
<div id="education" class="content-section-a">
  <div class="container">
    <div class="row">

      <div class="col-md-6 col-md-offset-3 text-center wrap_title">
        <h2>Education</h2>
        <!-- <p class="lead" style="margin-top:0">A special thanks to Death.</p> -->
      </div>

      <div class="col-sm-6  block wow bounceIn">
        <div class="row">
          <div class="col-md-4 box-icon rotate">
            <i class="fa fa-graduation-cap fa-4x "> </i>
          </div>
          <div class="col-md-8 box-ct">
            <h3> A.A Computer Science </h3>
            <p> Miami Dade College. Graduated September 2014 </p>
          </div>
        </div>
      </div>
      <div class="col-sm-6 block wow bounceIn">
        <div class="row">
          <div class="col-md-4 box-icon rotate">
            <i class="fa fa-keyboard-o fa-4x "> </i>
          </div>
          <div class="col-md-8 box-ct">
            <h3> Bachelor's in Computer Information Technology</h3>
            <p> Miami Dade College. Major in Mobile Application Development. In Progress</p>
          </div>
        </div>
      </div>
    </div>

    <div class="row tworow">
      <div class="col-sm-6  block wow bounceIn">
        <div class="row">
          <div class="col-md-4 box-icon rotate">
            <i class="fa fa-desktop fa-4x "> </i>
          </div>
          <div class="col-md-8 box-ct">
            <h3> Programmer </h3>
            <p> Self Taught in the glorious art of programming. Mobile and Web applications. </p>
          </div>
        </div>
      </div>
      <div class="col-sm-6 block wow bounceIn">
        <div class="row">
          <div class="col-md-4 box-icon rotate">
            <i class="fa fa-pencil fa-4x "> </i>
          </div>
          <div class="col-md-8 box-ct">
            <h3> High School Diploma</h3>
            <p> Hialeah High School. Always gained, never bought. </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_email_form.html.erb
<form role="form" action="mailto:perezalfredo14@gmail.com" method="post" >
  <div class="col-md-6">
    <div class="form-group">
      <label for="InputName">Your Name</label>
      <div class="input-group">
        <input type="text" class="form-control" name="InputName" id="InputName" placeholder="Enter Name" required>
        <span class="input-group-addon"><i class="glyphicon glyphicon-ok form-control-feedback"></i></span>
      </div>
    </div>

    <div class="form-group">
      <label for="InputEmail">Your Email</label>
      <div class="input-group">
        <input type="email" class="form-control" id="InputEmail" name="InputEmail" placeholder="Enter Email" required  >
        <span class="input-group-addon"><i class="glyphicon glyphicon-ok form-control-feedback"></i></span>
      </div>
    </div>

    <div class="form-group">
      <label for="InputMessage">Message</label>
      <div class="input-group">
        <textarea name="InputMessage" id="InputMessage" class="form-control" rows="5" required></textarea>
        <span class="input-group-addon"><i class="glyphicon glyphicon-ok form-control-feedback"></i></span>
      </div>
    </div>

    <input type="submit" name="submit" id="submit" value="Submit" class="btn wow tada btn-embossed btn-primary pull-right">
  </div>
</form>

app/views/home/_form.html.erb
<%= form_for @contact, url: home_index_path do |f| %>

  <div class="col-md-6">
    <div class="form-group">
      <label for="InputName">Your Name</label>
      <div class="input-group">
        <%= f.text_field :name, required: true, class: 'form-control', id: 'InputName', placeholder: "Enter Name" %>
        <span class="input-group-addon"><i class="glyphicon glyphicon-ok form-control-feedback"></i></span>
      </div>
    </div>

    <div class="form-group">
      <label for="InputEmail">Your Email</label>
      <div class="input-group">
        <%= f.email_field :email, required: true, class: "form-control", id: "InputEmail", placeholder: "Enter Email"  %>
        <span class="input-group-addon"><i class="glyphicon glyphicon-ok form-control-feedback"></i></span>
      </div>
    </div>

    <div class="form-group">
      <label for="InputMessage">Message</label>
      <div class="input-group">
        <%= f.text_area :message, as: :text, id: "InputMessage", class: 'form-control', rows: '5' %>
        <span class="input-group-addon"><i class="glyphicon glyphicon-ok form-control-feedback"></i></span>
      </div>
    </div>

    <%= f.submit 'Submit', name: 'sumbit', id: 'submit', class: 'btn wow tada btn-embossed btn-primary pull-right', action: 'submit'%>
  </div>
<% end %>

app/views/home/_portfolio.html.erb
<!-- Portfolio -->
<div id ="portfolio" class="content-section-a">

  <div class="container">

    <div class="content-section-b">

      <div class="container">
        <div class="row">
          <div class="col-sm-6 wow fadeInLeftBig">
            <div id="owl-demo-1" class="owl-carousel">
                <%= link_to image_tag("second.jpg", style: "display: hidden;"),  image_path('second.jpg'), class: "image-link" %>

                <%= link_to image_tag("duck.jpg"),  image_path('duck.jpg'), class: "image-link" %>

                <%= link_to image_tag("dash.jpg"),  image_path('dash.jpg'), class: "image-link" %>

                <%= link_to image_tag("board.jpg"),  image_path('board.jpg'), class: "image-link" %>

                <%= link_to image_tag("dashboard.jpg"),  image_path('dashboard.jpg'), class: "image-link" %>

            </div>
          </div>

          <div class="col-sm-6 wow fadeInRightBig"  data-animation-delay="200">
            <h3 class="section-heading">Gallery</h3>
            <div class="sub-title lead3">Swipe or Drag<br> To see current projects</div>
            <p class="lead">
              These include personal, hobby, and company projects. All responsive websites and web applications.
              More in the works...and coming soon!
            </p>
          </div>
        </div>
      </div>
    </div>


  </div>
  <!-- /.container -->
</div>

app/views/home/_screen.html.erb
<!-- Screenshot -->
<div id="screen" class="content-section-b">
  <div class="container">
    <div class="row" >
      <div class="col-md-6 col-md-offset-3 text-center wrap_title ">
        <h2>Phone Apps</h2>
      </div>
    </div>
    <div class="row wow bounceInUp" >
      <div id="owl-demo" class="owl-carousel">

        <a href="../assets/images/slide/scan1.png" class="image-link">
          <div class="item">
            <!-- <img  class="img-responsive img-rounded" src="../assets/images/slide/scan1.png" alt="Owl Image"> -->
            <%= image_tag("slide/scan1.png", class:"img-responsive img-rounded") %>
          </div>
        </a>

        <a href="../assets/images/slide/scan2.png" class="image-link">
          <div class="item">
            <!-- <img  class="img-responsive img-rounded" src="../assets/images/slide/scan2.png" alt="Owl Image"> -->
            <%= image_tag("slide/scan2.png", class:"img-responsive img-rounded") %>
          </div>
        </a>

        <a href="../assets/images/slide/scan3.png" class="image-link">
          <div class="item">
            <!-- <img  class="img-responsive img-rounded" src="../assets/images/slide/scan3.png" alt="Owl Image"> -->
            <%= image_tag("slide/scan3.png", class:"img-responsive img-rounded") %>
          </div>
        </a>

        <a href="../assets/images/slide/scan4.png" class="image-link">
          <div class="item">
            <!-- <img  class="img-responsive img-rounded" src="../assets/images/slide/scan4.png" alt="Owl Image"> -->
            <%= image_tag("slide/scan4.png", class:"img-responsive img-rounded") %>
          </div>
        </a>

        <a href="../assets/images/slide/logout.png" class="image-link">
          <div class="item">
            <!-- <img  class="img-responsive img-rounded" src="../assets/images/slide/logout.png" alt="Owl Image"> -->
            <%= image_tag("slide/logout.png", class:"img-responsive img-rounded") %>
          </div>
        </a>
      </div>
    </div>
  </div>


</div>

app/views/home/_skills.html.erb
<!-- Skills -->
<div id="skills" class="content-section-b" style="border-top: 0">
  <div class="container">

    <div class="col-md-6 col-md-offset-3 text-center wrap_title">
      <h2>Skills</h2>
      <p class="lead" style="margin-top:0">Only obtained through self-improvement.</p>

    </div>

    <div class="row">

      <div class="col-sm-4 wow fadeInDown text-center">
        <!-- <img  class="rotate" src="../assets/images/icon/ruby_rails.png" style="width: 100px; height: 100px;" alt="Generic placeholder image"> -->
        <%= image_tag("icon/ruby_rails.png", class:"rotate", size: '100') %>
        <h3>Ruby on Rails</h3>
        <!-- <p class="lead">Over a year developing with Ruby on Rails and MVC Architechture </p> -->
        <!-- <p><a class="btn btn-embossed btn-primary view" role="button">View Details</a></p> -->
      </div><!-- /.col-lg-4 -->

      <div class="col-sm-4 wow fadeInDown text-center">
        <!-- <img class="rotate" src="../assets/images/icon/html_5.png" style="width: 100px; height: 100px;" alt="Generic placeholder image"> -->
        <%= image_tag("icon/html_5.png", class:"rotate", size: '100') %>
        <h3>HTML</h3>
        <!-- <p class="lead">Ample HTML 5 knowledge </p> -->

        <!-- <p><a class="btn btn-embossed btn-primary view" role="button">View Details</a></p> -->
      </div><!-- /.col-lg-4 -->

      <div class="col-sm-4 wow fadeInDown text-center">
        <!-- <img  class="rotate" src="../assets/images/icon/css_3.png" style="width: 100px; height: 100px;" alt="Generic placeholder image"> -->
        <%= image_tag("icon/css_3.png", class:"rotate", size: '100') %>
         <h3>CSS</h3>
         <!-- <p class="lead"> CSS 3 and Sass preprocessor </p> -->
         <!-- <p><a class="btn btn-embossed btn-primary view" role="button">View Details</a></p> -->
      </div><!-- /.col-lg-4 -->


    </div><!-- /.row -->

    <div class="row tworow">

      <div class="col-sm-4  wow fadeInDown text-center">
        <!-- <img class="rotate" src="../assets/images/icon/javascript.png" style="width: 100px; height: 100px;" alt="Generic placeholder image"> -->
        <%= image_tag("icon/javascript.png", class:"rotate", size: '100') %>
        <h3>Javascript</h3>
        <!-- <p class="lead">Epsum factorial non deposit quid pro quo hic escorol. Olypian quarrels et gorilla congolium sic ad nauseum. </p> -->
       <!-- <p><a class="btn btn-embossed btn-primary view" role="button">View Details</a></p> -->
      </div><!-- /.col-lg-4 -->

      <div class="col-sm-4 wow fadeInDown text-center">
        <!-- <img  class="rotate" src="../assets/images/icon/java.png" style="width: 100px; height: 100px;" alt="Generic placeholder image"> -->
        <%= image_tag("icon/java.png", class:"rotate", size: '100') %>
         <h3>Java</h3>
         <!-- <p class="lead">Epsum factorial non deposit quid pro quo hic escorol. Olypian quarrels et gorilla congolium sic ad nauseum. </p> -->
         <!-- <p><a class="btn btn-embossed btn-primary view" role="button">View Details</a></p> -->
      </div><!-- /.col-lg-4 -->

      <div class="col-sm-4 wow fadeInDown text-center">
        <!-- <img  class="rotate" src="../assets/images/icon/browser.svg" alt="Generic placeholder image"> -->
        <%= image_tag("icon/browser.svg", class:"rotate", size: '100') %>
         <h3>Bootstrap</h3>
       <!-- <p class="lead">Epsum factorial non deposit quid pro quo hic escorol. Olypian quarrels et gorilla congolium sic ad nauseum. </p> -->
        <!-- <p><a class="btn btn-embossed btn-primary view" role="button">View Details</a></p> -->
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->
    <div class="row tworow">

      <div class="col-sm-4 wow fadeInDown text-center">
        <!-- <img  class="rotate" src="../assets/images/icon/c.png" style="width: 100px; height: 100px;" alt="Generic placeholder image"> -->
        <%= image_tag("icon/c.png", class:"rotate", size: '100') %>
         <h3>C/C ++</h3>
         <!-- <p class="lead">Epsum factorial non deposit quid pro quo hic escorol. Olypian quarrels et gorilla congolium sic ad nauseum. </p> -->
         <!-- <p><a class="btn btn-embossed btn-primary view" role="button">View Details</a></p> -->
      </div><!-- /.col-lg-4 -->

      <div class="col-sm-4 wow fadeInDown text-center">
        <!-- <img  class="rotate" src="../assets/images/icon/angular2.png" style="width: 100px; height: 100px;" alt="Generic placeholder image"> -->
        <%= image_tag("icon/angular2.png", class:"rotate", size: '100') %>
         <h3>Angular 2</h3>
         <!-- <p class="lead">Epsum factorial non deposit quid pro quo hic escorol. Olypian quarrels et gorilla congolium sic ad nauseum. </p> -->
         <!-- <p><a class="btn btn-embossed btn-primary view" role="button">View Details</a></p> -->
      </div><!-- /.col-lg-4 -->
    </div>

  </div>
</div>

app/views/home/index.html.erb
<head>
  <link href="https://fonts.googleapis.com/css?family=Arvo" rel="stylesheet">
</head>
<body id="home">

	<!-- Preloader -->
	<div id="preloader">
		<div id="status"></div>
	</div>

	<!-- FullScreen -->
    <div class="intro-header">
  		<div class="col-xs-12 text-center abcen1">
  			<h1 class="h1_home wow fadeIn" data-wow-delay="0.4s">Alfredo Perez</h1>
  			<h3 class="h3_home wow fadeIn" data-wow-delay="0.6s">Web Developer</h3>
  		</div>
          <!-- /.container -->
  		<div class="col-xs-12 text-center abcen wow fadeIn">
  			<div class="button_down ">
  				<a class="imgcircle wow bounceInUp" data-wow-duration="1.5s"  href="#skills"><%= image_tag("icon/circle.png", class: "icon_scroll") %></a>
  			</div>
  		</div>
    </div>

	<!-- NavBar-->
	<nav class="navbar-default" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>

			<div class="collapse navbar-collapse navbar-right navbar-ex1-collapse">
				<ul class="nav navbar-nav">

					<li class="menuItem"><a href="#skills">Skills</a></li>
					<li class="menuItem"><a href="#portfolio">Portfolio</a></li>
					<li class="menuItem"><a href="#screen">Screenshot</a></li>
					<li class="menuItem"><a href="#education">Education</a></li>
					<li class="menuItem"><a href="#contact">Contact</a></li>
				</ul>
			</div>

		</div>
	</nav>

  <%= render 'skills' %>
  <%= render 'portfolio' %>
  <%= render 'screen' %>
  <%= render 'education' %>

	<!-- Banner Download -->
	<div id="downloadlink" class="banner">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-md-offset-3 text-center wrap_title">
					<a href='http://www.freepik.com/free-vector/colored-polygonal-banners_813265.htm'></a>
					<h2>-Nelson Mandela</h2>
					<p class="lead quote" style="margin-top:20%;">"Education is the most powerful weapon we can use to change the world."</p>
				</div>
			</div>
		</div>
	</div>

<%= render 'contact' %>

</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlfredoWebPortfolio</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>